version: '3'

services:
  nextsmrt:
    build:
      context: .
      args:
        NODE_ENV: production
        API_KEY: ${API_KEY}
    labels:
      traefik.frontend.rule: 'Host:a.entradainteractive.com'
