version: '3'

services:
  steamavatar:
    restart: always
    container_name: steamavatar
    build:
      context: .
      args:
        NODE_ENV: staging
        STEAM_API_KEY: ${STEAM_API_KEY}
    networks:
      - web
    environment:
      NODE_ENV: 'production'
    labels:
      traefik.docker.network: 'web'
      traefik.enable: 'true'
      traefik.backend: 'steam-avatar'
      traefik.frontend.rule: 'Host:${STAGING_HOST}'
      traefik.port: '3000'

networks:
  web:
    external: true
