version: '3'

services:
  nextsmrt:
    restart: always
    container_name: nextsmrt
    build:
      context: .
      args:
        NODE_ENV: staging
        API_KEY: ${API_KEY}
    networks:
      - web
    environment:
      NODE_ENV: 'production'
    labels:
      traefik.docker.network: 'web'
      traefik.enable: 'true'
      traefik.backend: 'steam-avatar'
      traefik.frontend.rule: 'Host:a.entradainteractive.localhost'
      traefik.port: '3000'

networks:
  web:
    external: true
