version: '3'

services:
  steamavatar:
    build:
      context: .
      args:
        NODE_ENV: production
        STEAM_API_KEY: ${STEAM_API_KEY}
    labels:
      traefik.frontend.rule: 'Host:a.entradainteractive.com'
